// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Wed, 07 Jun 2017 16:53:37 BST.
// By https://git.io/c-for-go. DO NOT EDIT.

package gomxnet

/*
#cgo LDFLAGS: -lmxnet
#cgo CFLAGS: -I..
#include "c_api.h"
#include "c_predict_api.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import "unsafe"

// NDArrayHandle type as declared in bindingsgen/c_api.h:49
type NDArrayHandle unsafe.Pointer

// MXGenericCallback type as declared in bindingsgen/c_api.h:108
type MXGenericCallback func() int32

// CustomOpFBFunc type as declared in bindingsgen/c_api.h:133
type CustomOpFBFunc func(arg0 int32, arg1 []unsafe.Pointer, arg2 []int32, arg3 []int32, arg4 int32, arg5 unsafe.Pointer) int32

// CustomOpDelFunc type as declared in bindingsgen/c_api.h:136
type CustomOpDelFunc func(arg0 unsafe.Pointer) int32

// CustomOpListFunc type as declared in bindingsgen/c_api.h:137
type CustomOpListFunc func(arg0 [][][]byte, arg1 unsafe.Pointer) int32

// CustomOpInferShapeFunc type as declared in bindingsgen/c_api.h:138
type CustomOpInferShapeFunc func(arg0 int32, arg1 []int32, arg2 [][]uint32, arg3 unsafe.Pointer) int32

// CustomOpInferTypeFunc type as declared in bindingsgen/c_api.h:140
type CustomOpInferTypeFunc func(arg0 int32, arg1 []int32, arg2 unsafe.Pointer) int32

// CustomOpBwdDepFunc type as declared in bindingsgen/c_api.h:141
type CustomOpBwdDepFunc func(arg0 []int32, arg1 []int32, arg2 []int32, arg3 []int32, arg4 [][]int32, arg5 unsafe.Pointer) int32

// CustomOpCreateFunc type as declared in bindingsgen/c_api.h:144
type CustomOpCreateFunc func(arg0 string, arg1 int32, arg2 [][]uint32, arg3 []int32, arg4 []int32, arg5 []MXCallbackList, arg6 unsafe.Pointer) int32

// CustomOpPropCreator type as declared in bindingsgen/c_api.h:148
type CustomOpPropCreator func(arg0 string, arg1 int32, arg2 []string, arg3 []string, arg4 []MXCallbackList) int32

// MXKVStoreUpdater type as declared in bindingsgen/c_api.h:1370
type MXKVStoreUpdater func(key int32, recv NDArrayHandle, local NDArrayHandle, handle unsafe.Pointer)

// MXKVStoreServerController type as declared in bindingsgen/c_api.h:1465
type MXKVStoreServerController func(head int32, body string, controllerHandle unsafe.Pointer)

// NDListHandle type as declared in bindingsgen/c_predict_api.h:28
type NDListHandle unsafe.Pointer

// MXCallbackList as declared in bindingsgen/c_api.h:110
type MXCallbackList C.struct_MXCallbackList

// NDArrayOpInfo as declared in bindingsgen/c_api.h:91
type NDArrayOpInfo C.struct_NDArrayOpInfo

// NativeOpInfo as declared in bindingsgen/c_api.h:77
type NativeOpInfo struct {
	Forward        *func(arg0 int32, arg1 [][]float32, arg2 []int32, arg3 [][]uint32, arg4 []int32, arg5 unsafe.Pointer)
	Backward       *func(arg0 int32, arg1 [][]float32, arg2 []int32, arg3 [][]uint32, arg4 []int32, arg5 unsafe.Pointer)
	InferShape     *func(arg0 int32, arg1 []int32, arg2 [][]uint32, arg3 unsafe.Pointer)
	ListOutputs    *func(arg0 [][][]byte, arg1 unsafe.Pointer)
	ListArguments  *func(arg0 [][][]byte, arg1 unsafe.Pointer)
	PForward       unsafe.Pointer
	PBackward      unsafe.Pointer
	PInferShape    unsafe.Pointer
	PListOutputs   unsafe.Pointer
	PListArguments unsafe.Pointer
	ref7ce11869    *C.struct_NativeOpInfo
	allocs7ce11869 interface{}
}
