// Code generated by go-swagger; DO NOT EDIT.

package predict

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/rai-project/dlframework/httpapi/models"
)

// NewUrlsStreamParams creates a new UrlsStreamParams object
// with the default values initialized.
func NewUrlsStreamParams() *UrlsStreamParams {
	var ()
	return &UrlsStreamParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUrlsStreamParamsWithTimeout creates a new UrlsStreamParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUrlsStreamParamsWithTimeout(timeout time.Duration) *UrlsStreamParams {
	var ()
	return &UrlsStreamParams{

		timeout: timeout,
	}
}

// NewUrlsStreamParamsWithContext creates a new UrlsStreamParams object
// with the default values initialized, and the ability to set a context for a request
func NewUrlsStreamParamsWithContext(ctx context.Context) *UrlsStreamParams {
	var ()
	return &UrlsStreamParams{

		Context: ctx,
	}
}

// NewUrlsStreamParamsWithHTTPClient creates a new UrlsStreamParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUrlsStreamParamsWithHTTPClient(client *http.Client) *UrlsStreamParams {
	var ()
	return &UrlsStreamParams{
		HTTPClient: client,
	}
}

/*UrlsStreamParams contains all the parameters to send to the API endpoint
for the urls stream operation typically these are written to a http.Request
*/
type UrlsStreamParams struct {

	/*Body*/
	Body *models.DlframeworkUrlsRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the urls stream params
func (o *UrlsStreamParams) WithTimeout(timeout time.Duration) *UrlsStreamParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the urls stream params
func (o *UrlsStreamParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the urls stream params
func (o *UrlsStreamParams) WithContext(ctx context.Context) *UrlsStreamParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the urls stream params
func (o *UrlsStreamParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the urls stream params
func (o *UrlsStreamParams) WithHTTPClient(client *http.Client) *UrlsStreamParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the urls stream params
func (o *UrlsStreamParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the urls stream params
func (o *UrlsStreamParams) WithBody(body *models.DlframeworkUrlsRequest) *UrlsStreamParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the urls stream params
func (o *UrlsStreamParams) SetBody(body *models.DlframeworkUrlsRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *UrlsStreamParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
