// Code generated by go-swagger; DO NOT EDIT.

package registry

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/rai-project/dlframework/httpapi/models"
)

// ModelsOKCode is the HTTP code returned for type ModelsOK
const ModelsOKCode int = 200

/*ModelsOK models o k

swagger:response modelsOK
*/
type ModelsOK struct {

	/*
	  In: Body
	*/
	Payload *models.DlframeworkModelsResponse `json:"body,omitempty"`
}

// NewModelsOK creates ModelsOK with default headers values
func NewModelsOK() *ModelsOK {
	return &ModelsOK{}
}

// WithPayload adds the payload to the models o k response
func (o *ModelsOK) WithPayload(payload *models.DlframeworkModelsResponse) *ModelsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the models o k response
func (o *ModelsOK) SetPayload(payload *models.DlframeworkModelsResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ModelsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
