// Code generated by go-swagger; DO NOT EDIT.

package predictor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/rai-project/dlframework/web/models"
)

// PredictReader is a Reader for the Predict structure.
type PredictReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PredictReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPredictOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPredictOK creates a PredictOK with default headers values
func NewPredictOK() *PredictOK {
	return &PredictOK{}
}

/*PredictOK handles this case with default header values.

PredictOK predict o k
*/
type PredictOK struct {
	Payload *models.DlframeworkPredictResponse
}

func (o *PredictOK) Error() string {
	return fmt.Sprintf("[POST /v1/framework/{framework_name}/model/{model_name}/predict][%d] predictOK  %+v", 200, o.Payload)
}

func (o *PredictOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DlframeworkPredictResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
