//go:generate protoc --plugin=protoc-gen-go=${GOPATH}/bin/protoc-gen-go --proto_path=../../../..:../../../../github.com:. --gogoslick_out=plugins=grpc:. model.proto
//go:generate go-bindata -nomemcopy -prefix builtin_models/ -pkg mxnet -o builtin_models.go -ignore=.DS_Store ./builtin_models/...
package mxnet
