// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// DlframeworkClassification dlframework classification
// swagger:model dlframeworkClassification
type DlframeworkClassification struct {

	// index
	Index int32 `json:"index,omitempty"`

	// label
	Label string `json:"label,omitempty"`
}

// Validate validates this dlframework classification
func (m *DlframeworkClassification) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DlframeworkClassification) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DlframeworkClassification) UnmarshalBinary(b []byte) error {
	var res DlframeworkClassification
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
