// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DlframeworkFeatureResponse dlframework feature response
// swagger:model dlframeworkFeatureResponse
type DlframeworkFeatureResponse struct {

	// features
	Features []*DlframeworkFeature `json:"features"`

	// id
	ID string `json:"id,omitempty"`

	// input id
	InputID string `json:"input_id,omitempty"`

	// metadata
	Metadata map[string]string `json:"metadata,omitempty"`

	// request id
	RequestID string `json:"request_id,omitempty"`
}

// Validate validates this dlframework feature response
func (m *DlframeworkFeatureResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFeatures(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DlframeworkFeatureResponse) validateFeatures(formats strfmt.Registry) error {

	if swag.IsZero(m.Features) { // not required
		return nil
	}

	for i := 0; i < len(m.Features); i++ {
		if swag.IsZero(m.Features[i]) { // not required
			continue
		}

		if m.Features[i] != nil {
			if err := m.Features[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("features" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *DlframeworkFeatureResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DlframeworkFeatureResponse) UnmarshalBinary(b []byte) error {
	var res DlframeworkFeatureResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
