package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// DlframeworkErrorStatus dlframework error status
// swagger:model dlframeworkErrorStatus
type DlframeworkErrorStatus struct {

	// message
	Message string `json:"message,omitempty"`

	// ok
	Ok bool `json:"ok,omitempty"`
}

// Validate validates this dlframework error status
func (m *DlframeworkErrorStatus) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *DlframeworkErrorStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DlframeworkErrorStatus) UnmarshalBinary(b []byte) error {
	var res DlframeworkErrorStatus
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
