FROM rai/cuda_ppc64le:cudnn-8.0
MAINTAINER Carl Pearson <pearson@illinois.edu>

# install the core library
RUN apt-get update && apt-get install -y build-essential git libopenblas-dev libopencv-dev

# Install mxnet
WORKDIR /
RUN git clone --recursive https://github.com/dmlc/mxnet && cd mxnet && \ 
    cp make/config.mk . && \
    echo "USE_CUDA=1" >>config.mk && \
    echo "USE_CUDA_PATH=/usr/local/cuda" >>config.mk && \
    echo "USE_CUDNN=1" >>config.mk && \
    echo "USE_BLAS=openblas" >>config.mk && \
    make -j$(nproc) ADD_LDFLAGS=-L/usr/local/cuda/lib64/stubs
RUN ln -s /mxnet/lib/libmxnet.so /usr/lib/libmxnet.so

ENV LD_LIBRARY_PATH /usr/local/cuda/lib64:$LD_LIBRARY_PATH

#Install Go
RUN VERSION=1.8.3 \
    && OS=linux \
    && ARCH=ppc64le \
    && NAME=go$VERSION.${OS}-$ARCH.tar.gz \
    && wget https://storage.googleapis.com/golang/$NAME \
    && tar -C /usr/local -xf $NAME \
    && rm $NAME

ENV GOROOT "/usr/local/go"
ENV PATH "$GOROOT/bin:$PATH"
ENV GOPATH "/go"

# Get Go bindings
RUN go get -u -v github.com/songtianyi/go-mxnet-predictor
RUN sed -i "/prefix=/c prefix=\/mxnet" $GOPATH/src/github.com/songtianyi/go-mxnet-predictor/travis/mxnet.pc
RUN cp $GOPATH/src/github.com/songtianyi/go-mxnet-predictor/travis/mxnet.pc /usr/lib/pkgconfig
RUN pkg-config --libs mxnet
RUN cd $GOPATH/src/github.com/songtianyi/go-mxnet-predictor && go get -v .../.
ENV LD_LIBRARY_PATH /mxnet/lib:$LD_LIBRARY_PATH
#RUN mkdir /data
#RUN cd /data && wget https://www.dropbox.com/s/7l8zye9jpv2bywu/102flowers-0260.params
#RUN cd /data && wget https://www.dropbox.com/s/507hikz8561hwxg/102flowers-symbol.json
#RUN cd /data && wget https://www.dropbox.com/s/rg45ma97x886i53/mean.bin
#RUN cd /data && wget https://www.dropbox.com/s/9ej43gpkcdw3q32/flowertest.jpg


#Install Glide
RUN git clone https://github.com/Masterminds/glide.git $GOPATH/src/github.com/Masterminds/glide \
    && cd $GOPATH/src/github.com/Masterminds/glide \
    && make build \
    && cp -v glide /usr/bin/. \
    && rm -rf $GOPATH/src/github.com/Masterminds/glide

## Get the rai-project mxnet agent
WORKDIR $GOPATH/src/github.com/rai-project
RUN git clone https://github.com/rai-project/dlframework.git
## Uncomment the following 3 lines to use the local mxnet-agent instead of the github version
WORKDIR dlframework/mxnet/mxnet-agent
RUN rm -rf *
ADD *.go ./
WORKDIR $GOPATH/src/github.com/rai-project/dlframework
RUN glide install
WORKDIR mxnet/mxnet-agent
#RUN go get -v .../.
RUN go build
ENTRYPOINT ["./mxnet-agent", "--debug", "--verbose"]
